// compound-tabs-vue2-start/src/App.vue
<template>
  <div id="app">
    <Tabs initial-active-tab="profile">
      <div :class="$style.section">
        <Tab id="home">Home</Tab>
        <Tab id="profile">Profile</Tab>
        <Tab id="settings">Settings</Tab>
        <Tab id="about">About </Tab>
      </div>
      <div :class="$style.section">
        <TabPanel id="home">Home panel</TabPanel>
        <TabPanel id="profile">Profile panel</TabPanel>
        <TabPanel id="settings">Settings panel</TabPanel>
        <TabPanel id="about">About panel</TabPanel>
      </div>
    </Tabs>
  </div>
</template>

<script>
import { Tabs, Tab, TabPanel } from '@/components/tab'
export default {
  name: 'App',
  components: {
    Tabs,
    Tab,
    TabPanel,
  },
}
</script>

<style module>
.section {
  display: flex;
  justify-content: center;
  margin: 2rem;
}
</style>

// react-compound-tabs/src/App.tsx
import { Tabs, Tab, TabPanel } from './components/tabs'
import './App.css'

function App() {
  return (
    <div className='App'>
      <Tabs initialActiveTab='account'>
        <div style={{ display: 'flex' }}>
          <Tab id='account'>Account</Tab>
          <Tab id='settings'>Settings</Tab>
          <Tab id='privacy'>Privacy</Tab>
        </div>
        <div
          style={{
            display: 'flex',
            padding: '2rem',
            border: '1px solid gray;',
          }}
        >
          <TabPanel id='account'>Account Panel</TabPanel>
          <TabPanel id='settings'>Settings Panel</TabPanel>
          <TabPanel id='privacy'>Privacy Panel</TabPanel>
        </div>
      </Tabs>
    </div>
  )
}

export default App
