// compound-tabs-vue3/src/components/tab/Tab.vue
<template>
  <button
    :class="[$style.tabBtn, activeTab === id && $style.tabActive]"
    :id="`tab-${id}`"
    @click.prevent="activateTab(id)"
  >
    <slot />
  </button>
</template>

<script>
import { useTabs } from './Tabs'
export default {
  props: {
    id: {
      type: String,
      required: true,
    },
  },
  setup() {
    const { activeTab, activateTab } = useTabs()

    return {
      activeTab,
      activateTab,
    }
  },
}
</script>

<style lang="scss" module>
.tabBtn {
  cursor: pointer;
  background: transparent;
  outline: transparent;
  border: none;
  border-bottom: 1px solid #ccc;
  padding: 0.4rem 0.6rem;
  &:hover {
    background-color: #eee;
  }
}

.tabActive {
  border-bottom: 2px solid indigo;
}
</style>

// react-compound-tabs/src/components/tabs/Tab.tsx
import { useTabsActionsContext, useTabsContext } from './Tabs'

type TabProps = {
  children: React.ReactNode
  id: string
}

const Tab = (props: TabProps) => {
  const { children, id } = props
  const activeTab = useTabsContext()
  const setActiveTab = useTabsActionsContext()
  const isActive = id === activeTab
  return (
    <button
      style={{
        padding: '1rem 2rem',
        border: 'none',
        background: 'transparent',
        borderBottom: isActive ? '2px solid blue' : '2px solid transparent',
      }}
      id={`tab-${id}`}
      role='tab'
      aria-selected={isActive}
      aria-controls={`tab-panel-${id}`}
      onClick={() => setActiveTab(id)}
    >
      {children}
    </button>
  )
}

export default Tab
